#from https://youtu.be/yuZ6EuMTAWk
@tree.context_menu(name = "Open a Ticket", guild = discord.Object(id=guild_id))
async def open_ticket_context_menu(interaction: discord.Interaction, user: discord.Member):
    await interaction.response.defer(ephemeral = True)
    ticket = utils.get(interaction.guild.text_channels, name = f"ticket-for-{user.name.lower().replace(' ', '-')}-{user.discriminator}")
    if ticket is not None: await interaction.followup.send(f"{user.mention} already has a ticket open at {ticket.mention}!", ephemeral = True)
    else:
        if type(client.ticket_mod) is not discord.Role: 
            client.ticket_mod = interaction.guild.get_role(role_id)
        overwrites = {
            interaction.guild.default_role: discord.PermissionOverwrite(view_channel = False),
            user: discord.PermissionOverwrite(view_channel = True, read_message_history = True, send_messages = True, attach_files = True, embed_links = True),
            interaction.guild.me: discord.PermissionOverwrite(view_channel = True, send_messages = True, read_message_history = True), 
            client.ticket_mod: discord.PermissionOverwrite(view_channel = True, read_message_history = True, send_messages = True, attach_files = True, embed_links = True),
        }
        try: channel = await interaction.guild.create_text_channel(name = f"ticket-for-{user.name}-{user.discriminator}", overwrites = overwrites, reason = f"Ticket for {user}, generated by {interaction.user}")
        except: return await interaction.followup.send("Ticket creation failed! Make sure I have `manage_channels` permissions!", ephemeral = True)
        await channel.send(f"{interaction.user.mention} created a ticket for {user.mention}!", view = main())
        await interaction.followup.send(f"I've opened a ticket for {user.mention} at {channel.mention}!", ephemeral = True)
